id: AA32AED5D
title: The Mountain Smoke Offering (Riwo Sangchö)
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 00:36:10.804581
  last_modified_at: 2022-03-01 00:36:10.804593
