id: AA32AED5D
title: The Mountain Smoke Offering Arranged for Recitation
type: translation
source_metadata:
  languages:
  - en
  - de
  - es
  - fr
  - zh
  - bo
  datatype: PlainText
  created_at: 2022-03-01 00:36:10.811474
  last_modified_at: 2022-03-01 00:36:10.811483
