id: AA32AED5D
title: Mountain Smoke Offering from The Life-Force Practice of the Vidyādharas
type: translation
source_metadata:
  languages:
  - en
  - es
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-03-01 00:36:10.799347
  last_modified_at: 2022-03-01 00:36:10.799387
